# Generated by Django 4.0.4 on 2022-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='', verbose_name='book description'),
            preserve_default=False,
        ),
    ]
