# Generated by Django 4.0.4 on 2022-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_description_added_to_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='book short description'),
        ),
        migrations.AddField(
            model_name='publishsinghouse',
            name='desctiption',
            field=models.TextField(default='here is a test description', max_length=200, verbose_name='publishing house description'),
            preserve_default=False,
        ),
    ]
