# Generated by Django 4.0.4 on 2022-04-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_descs_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishsinghouse',
            old_name='desctiption',
            new_name='description',
        ),
    ]
